name: build 
on: 
  push: 
    branches: 
      -master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Build an image Docker File
       run: | 
         docker build -r juice-shop${{ github.sha }} .
        
     
